### ISSUE TITLE
Issues while running marve

### ISSUE THREAD

**Issue by lfoppiano** [khundman/marve#1]
I’ve got some problem with python and matplotlib with OSX, but I’ve managed to work around it. 

I’ve noticed that coreNLP doesn’t work on my mac book with 4Gb of memory. I had to give him more (~6g) to have it running.  After that I’ve run marve but I’ve got another error: 

```
(inria-virtualenv-p2) Johan:marve lfoppiano$ frameworkpython marve/sample.py 
Traceback (most recent call last):
  File "marve/sample.py", line 28, in <module>
    m.extract(test, coreNLP, grobid, patterns, write_to, show_graph=False, pretty=True, simplify=False)
  File "/Users/lfoppiano/development/inria/inria-virtualenv-p2/lib/python2.7/site-packages/marve/Measurements.py", line 488, in extract
    A = Annotations(output["sentences"][i]["tokens"], output["sentences"][i][dep_key])
KeyError: 'enhanced-plus-plus-dependencies’
```

I’m using CoreNLP version `stanford-corenlp-full-2016-10-31`, the same as in the installation documentation. 

Cheers
Luca

**Comment by khundman** [comment]
@lfoppiano It looks CoreNLP might not be outputting the dependencies but I'm having trouble re-creating, would you mind sharing the command you are starting CoreNLP with and the output log from the CoreNLP server when you run `sample.py`?

**Comment by lfoppiano** [comment]
@khundman sure! :-) 
The command is the same as in the documentation, except the memory: `java -mx6g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer 9000`

Here the log
```
Johan:stanford-corenlp-full-2016-10-31 lfoppiano$ java -mx6g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer 9000
[main] INFO CoreNLP - --- StanfordCoreNLPServer#main() called ---
[main] INFO CoreNLP - setting default constituency parser
[main] INFO CoreNLP - warning: cannot find edu/stanford/nlp/models/srparser/englishSR.ser.gz
[main] INFO CoreNLP - using: edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz instead
[main] INFO CoreNLP - to use shift reduce parser download English models jar from:
[main] INFO CoreNLP - http://stanfordnlp.github.io/CoreNLP/download.html
[main] INFO CoreNLP -     Threads: 8
[main] INFO CoreNLP - Starting server...
[main] INFO CoreNLP - StanfordCoreNLPServer listening at /0:0:0:0:0:0:0:0:9000
[pool-1-thread-3] INFO CoreNLP - [/0:0:0:0:0:0:0:1:50044] API call w/annotators tokenize,ssplit,pos,lemma,ner,regexner,parse,depparse,mention,natlog,coref,openie,kbp
The patient returned to Europe at 28 weeks of gestation.
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.TokenizerAnnotator - No tokenizer type provided. Defaulting to PTBTokenizer.
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
[pool-1-thread-3] INFO edu.stanford.nlp.tagger.maxent.MaxentTagger - Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [0.6 sec].
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
[pool-1-thread-3] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [1.6 sec].
[pool-1-thread-3] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [1.5 sec].
[pool-1-thread-3] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [0.6 sec].
[pool-1-thread-3] INFO edu.stanford.nlp.time.JollyDayHolidays - Initializing JollyDayHoliday for SUTime from classpath edu/stanford/nlp/models/sutime/jollyday/Holidays_sutime.xml as sutime.binder.1.
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator regexner
[pool-1-thread-3] INFO TokenRegexNER - TokensRegexNERAnnotator regexner: Read 580729 unique entries out of 581888 from edu/stanford/nlp/models/kbp/regexner_caseless.tab, 0 TokensRegex patterns.
[pool-1-thread-3] INFO TokenRegexNER - TokensRegexNERAnnotator regexner: Read 4857 unique entries out of 4868 from edu/stanford/nlp/models/kbp/regexner_cased.tab, 0 TokensRegex patterns.
[pool-1-thread-3] INFO TokenRegexNER - TokensRegexNERAnnotator regexner: Read 585586 unique entries from 2 files
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator parse
[pool-1-thread-3] INFO edu.stanford.nlp.parser.common.ParserGrammar - Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [0.3 sec].
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator depparse
[pool-1-thread-3] INFO edu.stanford.nlp.parser.nndep.DependencyParser - Loading depparse model file: edu/stanford/nlp/models/parser/nndep/english_UD.gz ... 
[pool-1-thread-3] INFO edu.stanford.nlp.parser.nndep.Classifier - PreComputed 99996, Elapsed Time: 15.389 (s)
[pool-1-thread-3] INFO edu.stanford.nlp.parser.nndep.DependencyParser - Initializing dependency parser ... done [20.7 sec].
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator mention
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.MentionAnnotator - Using mention detector type: dependency
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator natlog
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator coref
[pool-1-thread-3] INFO edu.stanford.nlp.coref.statistical.SimpleLinearClassifier - Loading coref model edu/stanford/nlp/models/coref/statistical/ranking_model.ser.gz ... done [3.2 sec].
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator openie
[pool-1-thread-3] INFO edu.stanford.nlp.naturalli.ClauseSplitter - Loading clause splitter from edu/stanford/nlp/models/naturalli/clauseSearcherModel.ser.gz ... done [0.0037 seconds]
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator kbp
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.KBPAnnotator - Loading KBP classifier from: edu/stanford/nlp/models/kbp/tac-re-lr.ser.gz
```

**Comment by lfoppiano** [comment]
I've noticed also the following, when I install marve using pip, i get version `0.0.7`, but when I build marve using `python setup.py install` it's installing version `0.0.6`: 

See `pip search marve` after having installed it using `python setup.py install`: 
```
(inria-virtualenv-p2) Johan:marve lfoppiano$ pip search marve
marve (0.0.7)         - Package for extracting measurements and related entities from text.
  INSTALLED: 0.0.6
  LATEST:    0.0.7
marvelous (1.0.2)     - Marvel API wrapper for python.
PyMarvel (0.1.0)      - Python wrapper for Marvel API
PyMarvelSimple (0.3)  - A wrapper for marvel API.
wymypy (1.2)          - WyMyPy is a standalone webserver music player frontend for the marvellous MPD (The music player daemon).
(inria-virtualenv-p2) Johan:marve lfoppiano$ 
```

**Comment by wxbks** [comment]
change dep_key in Measurements.py of marve from 'enhanced-plus-plus-dependencies' to 'enhancedPlusPlusDependencies' should solve the problem.

**Comment by lfoppiano** [comment]
Seems an old issue.. from me, I'm closing it as I don't have this problem anymore.
