### ISSUE TITLE
Exception in thread "pool-1-thread-3" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by wxbks** [khundman/marve#3]
Hi all,

When I run the sample.py, the short program just stuck there (I run it in a python iteractive shell).  I found in the stanford corenlp server, prints the following. 

It seems like a memory issue? but it is just one sentence: "The patient returned to Europe at 28 weeks of gestation."  Any idea on how to solve this?

[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator coref
Exception in thread "pool-1-thread-3" java.lang.OutOfMemoryError: Java heap space
	at java.io.ObjectInputStream$HandleTable.grow(ObjectInputStream.java:3493)
	at java.io.ObjectInputStream$HandleTable.assign(ObjectInputStream.java:3300)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1799)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at java.util.HashMap.readObject(HashMap.java:1396)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1909)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at edu.stanford.nlp.io.IOUtils.readObjectFromURLOrClasspathOrFileSystem(IOUtils.java:310)
	at edu.stanford.nlp.coref.statistical.FeatureExtractor.loadVocabulary(FeatureExtractor.java:90)
	at edu.stanford.nlp.coref.statistical.FeatureExtractor.<init>(FeatureExtractor.java:75)
	at edu.stanford.nlp.coref.statistical.StatisticalCorefAlgorithm.<init>(StatisticalCorefAlgorithm.java:63)
	at edu.stanford.nlp.coref.statistical.StatisticalCorefAlgorithm.<init>(StatisticalCorefAlgorithm.java:44)
	at edu.stanford.nlp.coref.CorefAlgorithm.fromProps(CorefAlgorithm.java:28)
	at edu.stanford.nlp.coref.CorefSystem.<init>(CorefSystem.java:34)
	at edu.stanford.nlp.pipeline.CorefAnnotator.<init>(CorefAnnotator.java:50)
	at edu.stanford.nlp.pipeline.AnnotatorImplementations.coref(AnnotatorImplementations.java:243)
	at edu.stanford.nlp.pipeline.AnnotatorFactories$13.create(AnnotatorFactories.java:402)
	at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:152)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:451)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:154)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:145)

**Comment by lfoppiano** [comment]
Dear @wxbks you should run stanford core NLP server with more memory, ideally I've managed to get it run with 8Gb: 
```
java -Xmx8g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer 9000
```

**Comment by khundman** [comment]
Closing, thanks @lfoppiano.
